### ISSUE TITLE
不建议将dist目录提交至git

### ISSUE THREAD

**Issue by ScSofts** [JimHans/live2d-kanban-desktop#1]
dist目录包含众多的exe可执行程序，严重影响clone速度，建议从仓库中移除以优化开发体验

**Comment by ScSofts** [comment]
![image](https://github.com/JimHans/live2d-kanban-desktop/assets/51468689/6aed1f69-59fe-4569-a302-adbbccc0674b)
附上一张图

**Comment by JimHans** [comment]
dist目录在早期负责旧版本存档，现在显然已不需要但一直未移除，因为并没有影响Commit所以一直没有管确实是疏忽了非常抱歉（，现在已经在仓库中移除它们。可以查看一下是否满足要求。
