### ISSUE TITLE
加载本地模型会显示不全

### ISSUE THREAD

**Issue by BrotherHai** [JimHans/live2d-kanban-desktop#15]
https://gitee.com/rao_she/live2d_models_collect加载了这个里面的模型
![image](https://github.com/JimHans/live2d-kanban-desktop/assets/50613992/5b061309-797b-4c90-9aa0-f12cc6cdfa00)

**Comment by JimHans** [comment]
好的，我看一下

**Comment by JimHans** [comment]
2.9.0已修复此问题，新增了对于V2版本模型的缩放调节，如果出现显示不全可以手动调节
