### ISSUE TITLE
很棒的应用

### ISSUE THREAD

**Issue by travisbikkle** [JimHans/live2d-kanban-desktop#19]
我是来搜kanban项目管理软件的，搜到这个项目，找了半天没有找到kanban怎么打开的，只有一上一下两个窗口，看起来是看板娘模型没有加载进来。

所以后续有加入kanban功能的计划吗？  :alien:

**Comment by JimHans** [comment]
您好，非常感谢您关注本项目，本项目本身是基于live2d的看板娘桌面挂件项目，与您需要的Kanban board 项目管理工具关系不大，且开发方向相差太大，因此本项目暂时并不考虑加入kanban功能，而是主要以继续开发日程管理、定时器与LLM对话等日常功能为主，请谅解，当然如果您真的需要相关功能，如果能力允许也可以自行为本项目添加功能，非常感谢您的贡献
