### ISSUE TITLE
Linux下使用的一些建议和反馈

### ISSUE THREAD

**Issue by zxp19821005** [JimHans/live2d-kanban-desktop#3]
如题。
### 编译环境
OS : EndeavourOS
Kernel : 6.1.56-1-lts
npm : 9.6.7
nodejs : 18.17.1

### 建议

1. 在一般的Linux发行版中，无法识别并显示`ico`文件，希望在`index.js`中将`app.ico`替换为`app.png`。
2. 任务栏图标无法正常显示，我不是专业编程的，对代码也只是一知半解，查了半天没找到原因，终端中运行也没有任何报错信息。
3. Packname name问题。在package.json中的name是`kanban-desktop`，而我将文件下载下来解压后的文件名是`live2d-kanban-desktop`，所以我移植的时候就自作主张将包名设置为了`live2d-kanban-desktop`
附上我已经移植的版本链接：
https://aur.archlinux.org/packages/live2d-kanban-desktop

**Comment by zxp19821005** [comment]
顺便再反馈一下 [2.7.0](https://github.com/JimHans/live2d-kanban-desktop/archive/refs/tags/v2.7.0.tar.gz)的包好大,看了 https://github.com/JimHans/live2d-kanban-desktop/issues/1 才发现`dist`目录好多exe文件~

**Comment by zxp19821005** [comment]
还有一个，能不能将默认搜索引擎更换为国内可用的呢？比如百度、bing之类的~

**Comment by JimHans** [comment]
首先关于Linux端的兼容性问题，我一般用Linux主要使用终端而不是桌面环境，所以之前只在大概2.4的时候也是用Endeavour测过一次效果，只能说惨不忍睹，所以你上面提到的问题其实都是已知的...只不过一直没有时间修，下个版本我会尽量修一下已知的Linux端问题，包括任务栏与图标问题。
至于Package Name只能说是历史遗留了，这个你如果要自己移植的话，自便就好。
默认搜索引擎这个问题主要是我个人认为百度太粪所以默认是Google，但也给了自定义选项😂，下一个版本我会改成默认Bing折中一下:P

**Comment by JimHans** [comment]
> 顺便再反馈一下 [2.7.0](https://github.com/JimHans/live2d-kanban-desktop/archive/refs/tags/v2.7.0.tar.gz)的包好大,看了 #1 才发现`dist`目录好多exe文件~

2.7.0tag对应的提交已经改到清除dist的版本了

**Comment by zxp19821005** [comment]
好的，谢谢！
