### ISSUE TITLE
希望可以增加对ChatGPT的Base_Url参数配置

### ISSUE THREAD

**Issue by Zhuying-Net** [JimHans/live2d-kanban-desktop#4]
尊敬的作者您好！您的项目十分优秀，我有一个小小的建议，在配置ChatGPT功能时，能否配置ChatGPT的base_url，因为中国大陆地区不支持访问api.openai.com，所以我希望用[聚合API平台](https://openai.qiheweb.com)进行反代访问。这样就免去要开魔法上网的烦恼了

**Comment by JimHans** [comment]
可以，下个版本我可以加一下。另外，即将发布的新版本已经加了openrouter作为第三方聚合平台，openrouter也支持国内直连访问，也有api聚合，你可以等这次版本更新后先试用一下能不能满足要求。

**Comment by JimHans** [comment]
2.8.1版本已经更新此功能，可以看看是否符合需要
