### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [JimHans/live2d-kanban-desktop#5]
日程提醒功能内能否支持选择时间，目前只能填分钟数诶  感觉能选择时间的话 应该可用性很高

**Comment by JimHans** [comment]
未来会优化这个功能的，大概下个版本就做吧，会新增自定义提示音以及选择时间的界面

**Comment by JimHans** [comment]
2.9.0已添加日期选择器与自定义通知音效功能
