### ISSUE TITLE
希望能加入更加泛化的OpenAI API格式支持

### ISSUE THREAD

**Issue by hundan2015** [JimHans/live2d-kanban-desktop#8]
作者你好。现阶段版本支持了ChatGPT的接口与OpenRouter的接口，但是不能满足接入其他大模型公司或者私人api的需求。希望您能通过加入对OpenAI API格式的支持来自定义的API key，模型提供商URL以及模型名称。

**Comment by JimHans** [comment]
可以，下个版本加上吧，毕竟这些接口的API格式基本一样

**Comment by hundan2015** [comment]
> 可以，下个版本加上吧，毕竟这些接口的API格式基本一样

你好，我加上了。如果您喜欢麻烦您merge！

**Comment by JimHans** [comment]
我看到了，周末看下没问题就合

**Comment by JimHans** [comment]
终于找着时间合并了，顺便把格式改回来了😂，修了一些小问题，可以看看效果可以不
